import type { CategoryKey } from "@/lib/types";

export const DISCLAIMER =
  "HireGuard is a student project. It is not a law firm and does not provide legal advice. The summaries, risk scores, red flags, and questions produced by this product are generated by automated tools and may be incomplete or incorrect. HireGuard's outputs are intended to help an Alberta employer identify and prioritize possible risks in employment agreements so they can decide when to seek qualified legal advice. Always consult a lawyer licensed by the Law Society of Alberta before acting on any output from this product. Use of HireGuard does not create a solicitor-client relationship.";

export const CATEGORY_WEIGHTS: Record<CategoryKey, number> = {
  termination: 0.3,
  restrictive: 0.15,
  compliance: 0.2,
  compensation: 0.1,
  workplaceRights: 0.1,
  flexibility: 0.15,
};

export const CATEGORY_LABELS: Record<CategoryKey, string> = {
  termination: "Termination & Severance",
  restrictive: "Restrictive Covenants",
  compliance: "Statutory Compliance",
  compensation: "Compensation Structure",
  workplaceRights: "Workplace Rights & Privacy",
  flexibility: "Flexibility & Change",
};

export const BAND_THRESHOLDS = { low: 35, medium: 65, high: 85 };

export const CANLII_URLS: Record<string, string> = {
  "term-001": "https://www.canlii.org/en/ca/scc/doc/1992/1992canlii105/1992canlii105.html",
  "term-002": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
  "term-003": "https://www.canlii.org/en/ca/scc/doc/2001/2001scc38/2001scc38.html",
  "term-004": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
  "rest-001": "https://www.canlii.org/en/ca/scc/doc/2009/2009scc6/2009scc6.html",
  "rest-002": "https://www.canlii.org/en/ca/scc/doc/1978/1978canlii7/1978canlii7.html",
  "rest-003": "https://www.canlii.org/en/ca/scc/doc/1978/1978canlii7/1978canlii7.html",
  "rest-004": "https://www.canlii.org/en/ca/scc/doc/2009/2009scc6/2009scc6.html",
  "comp-001": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
  "comp-002": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
  "comp-003": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
  "pay-001": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
  "pay-002": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
  "pay-003": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
  "wr-001": "https://www.canlii.org/en/ab/laws/stat/sa-2003-c-p-6.5/latest/sa-2003-c-p-6.5.html",
  "flex-001": "https://www.canlii.org/en/on/onca/doc/2008/2008onca327/2008onca327.html",
  "flex-002": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
  "flex-003": "https://www.canlii.org/en/ab/laws/stat/rsa-2000-c-e-9/latest/rsa-2000-c-e-9.html",
};

export const VERIFIED_CITATION_TOKENS: ReadonlyArray<string> = [
  "employment standards code",
  "esc s. 4",
  "esc s. 21",
  "esc s. 35",
  "esc s. 55",
  "esc s. 56",
  "esc s. 57",
  "esc s. 62",
  "esc s. 63",
  "esc s. 64",
  "section 4",
  "section 21",
  "section 35",
  "section 55",
  "section 56",
  "section 57",
  "section 62",
  "section 63",
  "section 64",
  "rsa 2000, c e-9",
  "rsa 2000 c e-9",
  "personal information protection act",
  "pipa s. 15",
  "section 15",
  "sa 2003, c p-6.5",
  "sa 2003 c p-6.5",
  "machtinger",
  "[1992] 1 scr 986",
  "1992 canlii 105",
  "mckinley",
  "2001 scc 38",
  "shafron",
  "2009 scc 6",
  "elsley",
  "[1978] 2 scr 916",
  "1978 canlii 7",
  "wronko",
  "2008 onca 327",
] as const;

export const CITATION_REGEXES: ReadonlyArray<RegExp> = [
  /\[\s*\d{4}\s*\]\s*\d+\s*S\.?\s*C\.?\s*R\.?\s*\d+/gi,
  /\d{4}\s+SCC\s+\d+/gi,
  /\d{4}\s+ONCA\s+\d+/gi,
  /\d{4}\s+ABCA\s+\d+/gi,
  /\d{4}\s+ABQB\s+\d+/gi,
  /[A-Z][A-Za-z]+\s+v\.?\s+[A-Z][A-Za-z]+(\s+[A-Z][A-Za-z]+)*/g,
  /(section|s\.?)\s*\d+/gi,
  /RSA\s+\d{4},?\s*c\s*[A-Z0-9-]+/gi,
  /SA\s+\d{4},?\s*c\s*[A-Z0-9-]+/gi,
];
