"use client";

/**
 * HireGuard — Real Architecture Breakdown
 *
 * Accurate representation of the actual codebase.
 * Corrects the mockup slide which cited Claude Sonnet, GPT-4o-mini as
 * "validation", shadcn/ui, and Vercel — none of which apply here.
 */

export default function ArchitecturePage() {
  return (
    <div
      className="min-h-screen p-6 md:p-10 font-sans"
      style={{ background: "#f4f7fc", fontFamily: "ui-sans-serif, system-ui, sans-serif" }}
    >
      {/* ── Slide 1: Pipeline ─────────────────────────────── */}
      <Slide>
        {/* Header */}
        <div
          className="rounded-t-xl px-8 py-5 flex items-center justify-between"
          style={{ background: "#1a3060" }}
        >
          <h1 className="text-xl md:text-2xl font-bold text-white tracking-tight">
            How We Built It — Replit + 3-Layer AI Pipeline
          </h1>
          <span
            className="text-sm font-semibold px-3 py-1.5 rounded flex items-center gap-2 whitespace-nowrap"
            style={{ background: "#c8921a", color: "#fff" }}
          >
            ▶ Ali Awan
          </span>
        </div>

        <div className="p-8 space-y-8">
          {/* Section label */}
          <h2 className="text-base font-semibold" style={{ color: "#1a3060" }}>
            The Build Architecture
          </h2>

          {/* Pipeline boxes */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
            <PipelineBox
              title="Replit Agent"
              badge=""
              accent="#1a3060"
              lines={[
                "Primary build tool",
                "AI-scaffolded UI",
                "Iterative prompt-driven dev",
              ]}
            />
            <PipelineBox
              title="Gemini 2.5 Flash"
              badge=""
              accent="#1a3060"
              lines={[
                "Layer 1 — extraction",
                "JSON schema output via Zod",
                "Fallback: gemini-1.5-flash",
                "Temp 0.1 · 8 192 token cap",
              ]}
            />
            <PipelineBox
              title="Rules Engine ★"
              badge="★"
              accent="#c8921a"
              lines={[
                "Layer 2 — scoring",
                "20 deterministic rules",
                "6 files in lib/scoring/*.ts",
                "Zero LLM involvement",
              ]}
              highlight
            />
            <PipelineBox
              title="ChatGPT + Gemini (raw)"
              badge=""
              accent="#1a3060"
              lines={[
                "Layer 3 — editorial only",
                "gpt-4o-mini · temp 0.5",
                "Gemini 2.5 Flash (raw)",
                "Never feeds into scoring",
              ]}
            />
          </div>

          {/* Key insight banner */}
          <div
            className="rounded-lg px-6 py-4 text-sm font-medium leading-relaxed text-white"
            style={{ background: "#1a3060" }}
          >
            <span style={{ color: "#c8921a" }}>★ </span>
            LLM extracts facts from the contract text. Deterministic TypeScript rules assign
            scores and attach CanLII citations. Every score traces to a specific Alberta
            statute or case. <strong>No hallucination is possible in the scoring layer</strong> —
            citations are hard-coded string constants, not generated by any model.
          </div>

          {/* Correction callout */}
          <div
            className="rounded-lg px-6 py-3 text-xs border-l-4"
            style={{
              background: "#fff8e1",
              borderColor: "#c8921a",
              color: "#6b4c0a",
            }}
          >
            <strong>Note:</strong> This corrects the mockup slide —{" "}
            <strong>Claude Sonnet</strong> is not used (extraction is Google Gemini);
            GPT-4o-mini is a comparison display tool, not a "validation layer"; styling is
            Tailwind CSS only (no shadcn/ui); hosting is Replit, not Vercel.
          </div>

          {/* Tech table */}
          <table className="w-full text-sm border-collapse">
            <tbody>
              {TECH_ROWS.map((row, i) => (
                <tr
                  key={row.label}
                  style={{ background: i % 2 === 0 ? "#f8fafc" : "#fff" }}
                >
                  <td
                    className="px-4 py-2.5 font-semibold w-40 whitespace-nowrap text-xs"
                    style={{ color: "#1a3060" }}
                  >
                    {row.label}
                  </td>
                  <td className="px-4 py-2.5" style={{ color: "#475569" }}>
                    {row.value}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Slide>

      {/* ── Slide 2: Data flow ────────────────────────────── */}
      <Slide className="mt-8">
        <div
          className="rounded-t-xl px-8 py-5"
          style={{ background: "#1a3060" }}
        >
          <h1 className="text-xl md:text-2xl font-bold text-white tracking-tight">
            Data Flow — What Happens When You Upload a Contract
          </h1>
        </div>

        <div className="p-8">
          <div className="space-y-3">
            {FLOW_STEPS.map((step, i) => (
              <div key={i} className="flex gap-4 items-start">
                <div
                  className="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5 text-white"
                  style={{ background: i === 2 ? "#c8921a" : "#1a3060" }}
                >
                  {i + 1}
                </div>
                <div>
                  <p className="text-sm font-semibold" style={{ color: "#1a3060" }}>
                    {step.title}
                  </p>
                  <p className="text-xs mt-0.5" style={{ color: "#64748b" }}>
                    {step.detail}
                  </p>
                  {step.code && (
                    <pre
                      className="mt-1 text-[11px] px-3 py-2 rounded font-mono"
                      style={{ background: "#1e293b", color: "#94a3b8" }}
                    >
                      {step.code}
                    </pre>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </Slide>

      {/* ── Slide 3: Scoring engine detail ───────────────── */}
      <Slide className="mt-8">
        <div
          className="rounded-t-xl px-8 py-5"
          style={{ background: "#1a3060" }}
        >
          <h1 className="text-xl md:text-2xl font-bold text-white tracking-tight">
            The Rules Engine — 20 Deterministic Rules, 6 Alberta-Law Categories
          </h1>
        </div>

        <div className="p-8 space-y-6">
          <p className="text-sm" style={{ color: "#475569" }}>
            Every rule lives in a versioned TypeScript file. The scoring function iterates
            rules, fires those whose predicate matches the extracted fields, sums their
            points, and caps each category at 100. Citations are string constants —
            never generated by an LLM.
          </p>

          {/* Category table */}
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr style={{ background: "#1a3060", color: "#fff" }}>
                <th className="px-4 py-2.5 text-left font-semibold text-xs">Category</th>
                <th className="px-4 py-2.5 text-left font-semibold text-xs">Weight</th>
                <th className="px-4 py-2.5 text-left font-semibold text-xs">Rules</th>
                <th className="px-4 py-2.5 text-left font-semibold text-xs">Key statutes / cases</th>
              </tr>
            </thead>
            <tbody>
              {CATEGORY_ROWS.map((row, i) => (
                <tr key={row.cat} style={{ background: i % 2 === 0 ? "#f8fafc" : "#fff" }}>
                  <td className="px-4 py-2.5 font-medium text-xs" style={{ color: "#1a3060" }}>
                    {row.cat}
                  </td>
                  <td className="px-4 py-2.5 text-xs font-mono" style={{ color: "#c8921a" }}>
                    {row.weight}
                  </td>
                  <td className="px-4 py-2.5 text-xs tabular-nums" style={{ color: "#475569" }}>
                    {row.rules}
                  </td>
                  <td className="px-4 py-2.5 text-xs" style={{ color: "#475569" }}>
                    {row.sources}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Score formula */}
          <div
            className="rounded-lg px-6 py-4"
            style={{ background: "#f4f7fc", border: "1px solid #e2e8f0" }}
          >
            <p className="text-xs font-semibold mb-2" style={{ color: "#1a3060" }}>
              Sensitivity formula (lib/scoring/index.ts)
            </p>
            <pre
              className="text-xs font-mono"
              style={{ color: "#c8921a" }}
            >
              overall = round( 0.5 × weightedAverage + 0.5 × maxCategoryScore )
            </pre>
            <p className="text-xs mt-2" style={{ color: "#64748b" }}>
              A single Critical category cannot be masked by good scores elsewhere. Missing
              sections auto-score 100 (Critical) with a synthesized rule hit.
            </p>
          </div>
        </div>
      </Slide>

      {/* ── Slide 4: File & API map ───────────────────────── */}
      <Slide className="mt-8">
        <div
          className="rounded-t-xl px-8 py-5"
          style={{ background: "#1a3060" }}
        >
          <h1 className="text-xl md:text-2xl font-bold text-white tracking-tight">
            File Map — What Lives Where
          </h1>
        </div>

        <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-6">
          {FILE_MAP.map((section) => (
            <div key={section.dir}>
              <h3 className="text-xs font-bold uppercase tracking-wider mb-2" style={{ color: "#c8921a" }}>
                {section.dir}
              </h3>
              <div className="space-y-1">
                {section.files.map((f) => (
                  <div key={f.name} className="flex gap-2 text-xs">
                    <code
                      className="font-mono shrink-0"
                      style={{ color: "#1a3060", minWidth: "14rem" }}
                    >
                      {f.name}
                    </code>
                    <span style={{ color: "#64748b" }}>{f.desc}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </Slide>
    </div>
  );
}

/* ── Sub-components ──────────────────────────────────────────────── */

function Slide({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return (
    <div
      className={`rounded-xl border border-slate-200 shadow-md overflow-hidden max-w-5xl mx-auto ${className}`}
      style={{ background: "#fff" }}
    >
      {children}
    </div>
  );
}

function PipelineBox({
  title,
  lines,
  accent,
  highlight = false,
}: {
  title: string;
  badge: string;
  lines: string[];
  accent: string;
  highlight?: boolean;
}) {
  return (
    <div
      className="rounded-lg p-4 text-white flex flex-col gap-2"
      style={{ background: highlight ? "#c8921a" : "#1a3060" }}
    >
      <p className="text-sm font-bold leading-tight">{title}</p>
      <div className="space-y-0.5">
        {lines.map((l, i) => (
          <p key={i} className="text-xs opacity-90 leading-snug">
            {l}
          </p>
        ))}
      </div>
    </div>
  );
}

/* ── Static data ─────────────────────────────────────────────────── */

const TECH_ROWS = [
  {
    label: "AI Coding Tool",
    value: "Replit Agent — instructor-recommended, primary build tool for all scaffolding and iteration",
  },
  {
    label: "Framework",
    value: "Next.js 14 App Router + React 18 + TypeScript — single repo, single deploy, SSR + API routes",
  },
  {
    label: "Styling",
    value: "Tailwind CSS 3 (utility-first, no component library) — navy/gold/green brand palette from logo",
  },
  {
    label: "LLM — Layer 1",
    value: "Google Gemini 2.5 Flash via @google/generative-ai SDK — extraction, temp 0.1, JSON schema, Zod validation. Fallback: gemini-1.5-flash",
  },
  {
    label: "LLM — Layer 3",
    value: "OpenAI gpt-4o-mini (editorial only) + raw Gemini 2.5 Flash — comparison display, citations flagged for hallucination. Never feeds into scoring.",
  },
  {
    label: "Scoring",
    value: "20 deterministic TypeScript rules in lib/scoring/*.ts — versioned, CanLII-sourced. No LLM in the loop.",
  },
  {
    label: "File parsing",
    value: "pdfjs-dist (PDF) + mammoth (DOCX) — browser-side, zero server upload required",
  },
  {
    label: "Storage",
    value: "localStorage only — no database, no backend session. Pre-seeded demo contracts in lib/seed.ts.",
  },
  {
    label: "Hosting",
    value: "Replit Deploy — one-click publish from workspace. Production URL auto-generated.",
  },
];

const FLOW_STEPS = [
  {
    title: "User uploads PDF / DOCX / TXT or pastes text",
    detail: "pdfjs-dist and mammoth extract raw text in the browser. Text is capped at 100,000 chars. No file is sent to a server — only the extracted string.",
    code: null,
  },
  {
    title: "POST /api/analyze — Gemini extraction (Layer 1)",
    detail: "Gemini 2.5 Flash reads the contract text with a strict system prompt. It is forbidden from generating statutes or case law. Returns a typed JSON object validated by Zod.",
    code: `// lib/gemini.ts
const MODEL_CHAIN = ["gemini-2.5-flash", "gemini-1.5-flash"]
// temp: 0.1, responseMimeType: "application/json", maxOutputTokens: 8192`,
  },
  {
    title: "scoreContract() — Deterministic rules engine (Layer 2) ★",
    detail: "The extracted JSON is passed to the rules engine. 20 hand-authored rules fire based on field values. Each rule carries a severity, points value, and a CanLII citation string constant. Missing categories score 100/100 automatically.",
    code: `// lib/scoring/index.ts
overall = round( 0.5 × weightedAvg + 0.5 × maxCategoryScore )`,
  },
  {
    title: "Report saved to localStorage, user redirected",
    detail: "The complete OverallReport object (score, categories, hits, summary, questions) is persisted in the browser. The server holds no state.",
    code: null,
  },
  {
    title: "POST /api/compare — editorial comparison (Layer 3, optional)",
    detail: "ChatGPT (gpt-4o-mini) and raw Gemini 2.5 Flash analyze the same contract text with no guardrails. Their outputs are checked against a verified citation whitelist and hallucinations are flagged ⚠. This panel is display-only — it does not affect the HireGuard score.",
    code: `// lib/comparison.ts
const [chatgpt, geminiRaw] = await Promise.all([
  rawChatGPTOpinion(text),    // gpt-4o-mini, temp 0.5
  rawGeminiOpinion(text),     // gemini-2.5-flash, temp 0.5
])`,
  },
];

const CATEGORY_ROWS = [
  {
    cat: "Termination & Severance",
    weight: "30%",
    rules: "4 rules",
    sources: "ESC ss. 55–57 · Machtinger v HOJ · McKinley v BC Tel",
  },
  {
    cat: "Statutory Compliance",
    weight: "20%",
    rules: "3 rules",
    sources: "ESC RSA 2000 c E-9 · at-will language · governing law",
  },
  {
    cat: "Flexibility & Change",
    weight: "15%",
    rules: "3 rules",
    sources: "ESC ss. 62–64 · Wronko v Western Inventory (ONCA)",
  },
  {
    cat: "Restrictive Covenants",
    weight: "15%",
    rules: "4 rules",
    sources: "Shafron v KRG (SCC 2009) · Elsley v Collins (SCC 1978)",
  },
  {
    cat: "Compensation Structure",
    weight: "10%",
    rules: "3 rules",
    sources: "ESC s. 21 (overtime 1.5×) · ESC s. 35 (vacation 4%)",
  },
  {
    cat: "Workplace Rights & Privacy",
    weight: "10%",
    rules: "2 rules",
    sources: "PIPA SA 2003 c P-6.5 s. 15 · IP overbreadth (AB common law)",
  },
];

const FILE_MAP = [
  {
    dir: "app/ — pages & API",
    files: [
      { name: "page.tsx", desc: "Home — features + AI testimonial" },
      { name: "analyze/page.tsx", desc: "Upload flow, file parsing, submit" },
      { name: "portfolio/page.tsx", desc: "User contracts table (localStorage)" },
      { name: "contracts/[id]/page.tsx", desc: "Full report page" },
      { name: "about/page.tsx", desc: "Project info + hallucination perspective" },
      { name: "api/analyze/route.ts", desc: "Gemini extraction + scoring API" },
      { name: "api/compare/route.ts", desc: "Parallel ChatGPT + Gemini comparison" },
    ],
  },
  {
    dir: "lib/ — logic",
    files: [
      { name: "scoring/index.ts", desc: "scoreContract(), missing-section detection" },
      { name: "scoring/termination.ts", desc: "4 rules — notice, severance, just cause" },
      { name: "scoring/restrictive.ts", desc: "4 rules — non-compete, non-solicit" },
      { name: "scoring/compliance.ts", desc: "3 rules — governing law, at-will" },
      { name: "scoring/compensation.ts", desc: "3 rules — overtime, vacation pay" },
      { name: "scoring/flexibility.ts", desc: "3 rules — unilateral change, layoff" },
      { name: "scoring/workplace-rights.ts", desc: "2 rules — surveillance, IP" },
      { name: "gemini.ts", desc: "Extraction with retry/fallback model chain" },
      { name: "comparison.ts", desc: "Parallel ChatGPT + raw Gemini opinions" },
      { name: "citation-detect.ts", desc: "Hallucination flagging vs. whitelist" },
      { name: "storage.ts", desc: "localStorage CRUD for reports" },
      { name: "types.ts", desc: "Shared TypeScript interfaces" },
    ],
  },
  {
    dir: "components/",
    files: [
      { name: "risk-score-gauge.tsx", desc: "SVG circular risk gauge" },
      { name: "category-bar-chart.tsx", desc: "Bar chart with MISSING badges" },
      { name: "red-flag-card.tsx", desc: "Rule-hit card with CanLII link" },
      { name: "ai-comparison-panel.tsx", desc: "Side-by-side editorial panel" },
      { name: "pdf-report.tsx", desc: "Client-side PDF export layout" },
      { name: "brand-kit.tsx", desc: "Interactive visual style guide" },
    ],
  },
  {
    dir: "public/",
    files: [
      { name: "hireguard-logo.png", desc: "Brand logo — navy/gold/green" },
    ],
  },
];
